version: '3'
services:
  reverse-proxy:
    image: traefik
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false
    restart: "no"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  microservice-hextorgb:
    build: microservice-hextorgb
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.microservice-hextorgb.rule=PathPrefix(`/microservice-hextorgb`)"
      - "traefik.http.routers.microservice-hextorgb.middlewares=microservice-hextorgb-stripprefix"
      - "traefik.http.services.microservice-hextorgb.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.microservice-hextorgb-stripprefix.stripprefix.prefixes=/microservice-hextorgb"
